### ISSUE TITLE
repositories.cfg could not be loaded.

### ISSUE THREAD

**Issue by tulasirm** [amiya-pattnaik/appium-setup-made-easy-OSX#1]
Hi, 
Thanks for easiest solution, when i am running android.sh file i am seeing this issue and then not able to start emulator.
---------------------------------------
Accept? (y/N): All SDK package licenses accepted
done
Updating the Android sdk manager tool
Warning: File /Users/prokarma/.android/repositories.cfg could not be loaded.

**Comment by amiya-pattnaik** [comment]
It seems to be you dont have write permission to the /Users/prokarma/

change it with CHMOD command and it should work
